-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGVEuBqoZJPsm7Awb
Yu+wVbFZmsIrcoDFl4OvECZ5f9agCgYIKoZIzj0DAQehRANCAASdqRND0gK19D2Q
JGfRl5sfRm60hOmND2vm7FiRCgZgxBbvaWB+VFeBCVFrvbWfSShFBdZmpKSgvMc7
K/ERblxy
-----END PRIVATE KEY-----